name: ChatGPT for Pull Request Reviewer
run-name: "Review for PR #${{ github.event.pull_request.number }} by @${{ github.actor }}"
on:
  pull_request:
    types: [opened, reopened]
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Run `git fetch`"
        run: git fetch
      - name: "Run `git diff`"
        run: git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} > diff.patch
      - name: Generate data
        run: "node -e \"console.log(JSON.stringify({
model:'gpt-3.5-turbo-0301',
message:[
{role:'system',content:'You are the software engineer.'},
{role:'system',content:'You are reviewer for the pull request.'},
{role:'user',content:'Review and optimize following code (you can fix the code in the code block and attach the detail reason):\\n\\n'+require('fs').readFileSync('diff.patch').toString()},
]
}))\" > data.json"
      - name: Request OpenAI API
        run: "curl https://api.openai.com/v1/chat/completions -H 'Content-Type: application/json' -H 'Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}' -d @data.json > response.json"
      - name: Test
        run: cat response.json
      - name: Test
        run: cat response.json | jq
