name: ChatGPT for Pull Request Reviewer
run-name: "Review for PR #${{ github.event.pull_request.number }} by @${{ github.actor }}"
on:
  pull_request:
    types: [opened, reopened]
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Run `git fetch`"
        run: git fetch
      - name: "Run `git diff`"
        run: git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} > diff.patch
      - name: Generate data
        run: "node -e \"console.log(JSON.stringify({
model:'gpt-3.5-turbo-0301',
messages:[
{role:'system',content:'You are the software engineer.'},
{role:'system',content:'You are reviewer for the pull request.'},
{role:'user',content:'Pelase review and optimize following code.\\nYou can fix the code in the diff code block.\\nYou can attach the detail reason about the fix.\\nYour answer must include the file path and the line of the file.\\n\\n'+require('fs').readFileSync('diff.patch').toString()},
]
}))\" > data.json"
      - name: Request OpenAI API
        run: "curl https://api.openai.com/v1/chat/completions -H 'Content-Type: application/json' -H 'Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}' -d @data.json > response.json"
      - name: Test
        run: cat response.json | jq
      - name: Generate data
        run: "node -e \"console.log(JSON.stringify({
event:'COMMENT',
body:JSON.parse(require('fs').readFileSync('response.json').toString()).choices.map(choice => choice.message.content).join('\\n'),
}))\" > data.json"
      - name: Request GitHub API
        run: "curl -X POST https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls/${{ github.event.pull_request.number }}/reviews -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}' -H 'X-GitHub-Api-Version: 2022-11-28' -d @data.json > response.json"
      - name: Test
        run: cat response.json | jq
